import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('gameAPI', {
  init:           ()           => ipcRenderer.invoke('game:init'),
  runEncounter:   ()           => ipcRenderer.invoke('game:runEncounter'),
  engageCombat:   ()           => ipcRenderer.invoke('game:engageCombat'),
  tryFlee:        ()           => ipcRenderer.invoke('game:tryFlee'),
  selectZone:     (zoneId: string)     => ipcRenderer.invoke('game:selectZone', zoneId),
  renderBag:      ()           => ipcRenderer.invoke('game:renderBag'),
  renderStats:    ()           => ipcRenderer.invoke('game:renderStats'),
  renderMap:      ()           => ipcRenderer.invoke('game:renderMap'),
  renderShop:     ()           => ipcRenderer.invoke('game:renderShop'),
  getShopData:    ()           => ipcRenderer.invoke('game:getShopData'),
  buyItem:        (id: string, qty: number, keeperName: string) => ipcRenderer.invoke('game:buyItem', id, qty, keeperName),
  sellItem:       (id: string, qty: number)    => ipcRenderer.invoke('game:sellItem', id, qty),
  renderParty:    ()           => ipcRenderer.invoke('game:renderParty'),
  getCraftingData: ()           => ipcRenderer.invoke('game:getCraftingData'),
  craftItem:       (recipeId: string)  => ipcRenderer.invoke('game:craftItem', recipeId),
  butcherCorpses:    ()           => ipcRenderer.invoke('game:butcherCorpses'),
  equipItem:      (id: string, iid: string)   => ipcRenderer.invoke('game:equipItem', id, iid),
  rezMember:      (instanceId: string) => ipcRenderer.invoke('game:rezMember', instanceId),
  allocateStat:   (instanceId: string, stat: string) => ipcRenderer.invoke('game:allocateStat', instanceId, stat),
  useItem:        (itemId: string)     => ipcRenderer.invoke('game:useItem', itemId),
  back:           ()           => ipcRenderer.invoke('game:back'),
  getItemCatalog:        ()        => ipcRenderer.invoke('game:getItemCatalog'),
  getBuffCatalog:        ()        => ipcRenderer.invoke('game:getBuffCatalog'),
  getQuestCatalog:       ()        => ipcRenderer.invoke('game:getQuestCatalog'),
  getEntityCatalog:      ()        => ipcRenderer.invoke('game:getEntityCatalog'),
  setCombatMode:         (mode: string)    => ipcRenderer.invoke('game:setCombatMode', mode),
  executePlayerAction:   (actions: unknown) => ipcRenderer.invoke('game:executePlayerAction', actions),
  getRosterData:         ()        => ipcRenderer.invoke('game:getRosterData'),
  swapPartyMember:       (outId: string, inId: string) => ipcRenderer.invoke('game:swapPartyMember', outId, inId),
  removeFromParty:       (id: string)          => ipcRenderer.invoke('game:removeFromParty', id),
  addToParty:            (id: string)          => ipcRenderer.invoke('game:addToParty', id),
  setPetForCompanion:    (id: string, petId: string)   => ipcRenderer.invoke('game:setPetForCompanion', id, petId),
  getAvailablePets:      (id: string)          => ipcRenderer.invoke('game:getAvailablePets', id),
  listSaveSlots:         ()        => ipcRenderer.invoke('game:listSaveSlots'),
  saveToSlot:            (slotId: string, saveName: string) => ipcRenderer.invoke('game:saveToSlot', slotId, saveName),
  loadFromSlot:          (slotId: string) => ipcRenderer.invoke('game:loadFromSlot', slotId),
  deleteSaveSlot:        (slotId: string) => ipcRenderer.invoke('game:deleteSaveSlot', slotId),
})
